fix browserchanger
I'm not even sure how this worked in bash at all.
It uses zsh style associative array expansion.
At any rate, it seems to have changed between 5.1p4 and 5.1p8.
Just use ZSH at this point

diff --git a/private_dot_local/bin/executable_browsers b/private_dot_local/bin/executable_browsers
--- a/private_dot_local/bin/executable_browsers
+++ b/private_dot_local/bin/executable_browsers
@@ -1,5 +1,6 @@
-#!/bin/bash
+#!/bin/zsh
 
+set -euo pipefail
 
 declare -A browsers
 
@@ -36,9 +37,17 @@ do_echo() {
     printf "%s" "${browsers[$1]}"
 }
 
-
-[[ "$1" = "GET" ]] && do_echo "$(get_current)"
-
-[[ "$1" = "SET" ]] && set_current "$2"
-
-[[ "$1" = "CYCLE" ]] && cycle
+case "$1" in
+    GET)
+        do_echo "$(get_current)"
+        ;;
+    SET)
+        set_current "$2"
+        ;;
+    CYCLE)
+        cycle
+        ;;
+    *)
+        echo "invalid argument: $1"
+        exit 1
+esac
